export enum PreviewAttachmentEnum {
  PREVIEW_PDF = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/PDF.svg',
  PREVIEW_TINY_PDF = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/PDF.svg',
  PREVIEW_WORD = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/DOCX.svg',
  PREVIEW_TINY_WORD = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/DOCX.svg',
  PREVIEW_EXCEL = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/XLS.svg',
  PREVIEW_TINY_EXCEL = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/XLS.svg',
  PREVIEW_PPT = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/PPT.svg',
  PREVIEW_TINY_PPT = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/PPT.svg',
  PREVIEW_AUDIO = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/Audio.svg',
  PREVIEW_TINY_AUDIO = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/Audio.svg',
  PREVIEW_ONE = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/DOCX.svg',
  PREVIEW_TINY_ONE = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/DOCX.svg',
  PREVIEW_OTHER = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview/DOCX.svg',
  PREVIEW_TINY_OTHER = 'https://develop.cdn.chattigo.com/assets/img/attachment/preview-tiny/DOCX.svg',
}
